target 'CrownControlDemo' do
    platform :ios, '9.0'
    use_frameworks!
    pod 'CrownControl', :path => '../'
end

target 'CrownControlTests' do
    platform :ios, '9.0'
    use_frameworks!
    pod 'CrownControl', :path => '../'
    pod 'Quick', '1.3.2'
    pod 'Nimble', '7.3.1'
end