coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 7%
  ignore:
    - cmake-debug-build/*
    - Example/*
    - Scripts/*
    - Documentaion/*
    - Tests/*
    - Pods/*
    - Applications/Xcode.app/*
    - vendor/*
    - Carthage/*
    - build/*
    - .build/*
    - .vagrant/*